sudo: false
language: node_js

# The debian (or snap) package for Hugo are not included in this distro
before_install:
  - uname -i
  - wget https://github.com/gohugoio/hugo/releases/download/v0.33/hugo_0.33_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo*.deb
  - hugo version
script: npm run test
after_script: git add docs/* && git commit -m 'Automatic deployment from Travis' && git push origin master
node_js:
  - "stable"
  