sudo: false
language: node_js
node_js:
  - "stable"

# The debian (or snap) package for Hugo are not included in this distro
before_install:
  - uname -i
  - wget https://github.com/gohugoio/hugo/releases/download/v0.33/hugo_0.33_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo*.deb
  - hugo version
script: npm run test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master